const BAD_REQUEST_STATUS_CODE = 400;
const BAD_REQUEST_STATUS_MESSAGE = 'Bad request';
const INTERNAL_SERVER_MESSAGE = 'Internal server error';
const INTERNAL_SERVER_STATUS_CODE = 500;
const METHOD_NOT_ALLOWED_STATUS_CODE = 405;
const NOT_FOUND_STATUS_CODE = 404;
const NOT_FOUND_STATUS_MESSAGE = 'Not found';
const SUCCESS_RESPONSE_STATUS_CODE = 200;
const SUCCESS_RESPONSE_NO_CONTENT_STATUS_CODE = 204;
const SUCCESS_RESPONSE_STATUS_MESSAGE = 'Successfully updated';
const UNPROCESSABLE_ENTITY_STATUS_CODE = 422;
const GOOGLE_CLIENT_ID = '';
const GOOGLE_CLIENT_SECRET = '';
const JWT_SECRET = '';

export {
  BAD_REQUEST_STATUS_CODE,
  BAD_REQUEST_STATUS_MESSAGE,
  INTERNAL_SERVER_MESSAGE,
  INTERNAL_SERVER_STATUS_CODE,
  METHOD_NOT_ALLOWED_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  NOT_FOUND_STATUS_MESSAGE,
  SUCCESS_RESPONSE_STATUS_CODE,
  SUCCESS_RESPONSE_STATUS_MESSAGE,
  UNPROCESSABLE_ENTITY_STATUS_CODE,
  SUCCESS_RESPONSE_NO_CONTENT_STATUS_CODE,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  JWT_SECRET
};